### ISSUE TITLE
What import device are you using

### ISSUE THREAD

**Issue by janeoa** [yushulx/python-capture-device-list#3]
tried pip3 install device but got AttributeError: module 'device' has no attribute 'getDeviceList'

**Comment by ManbirJudge** [comment]
Same issue here, it was installed successfully, but it does not contain that functions.

**Comment by yushulx** [comment]
It's not published to pypi.org, so you cannot use `pip3 install device`. The only way is to build the source code by yourself:

```bash
python setup.py build install
```
