### ISSUE TITLE
PyInstaller Compatibility

### ISSUE THREAD

**Issue by Cemos-121** [yushulx/python-capture-device-list#9]
Hello. Is this compatible with PyInstaller? I was able get this working with my project, but when using an .exe made by PyInstaller, the program doesn't get the list of devices.

**Comment by yushulx** [comment]
@Cemos-121 I don't have this issue.

```bash
pyinstaller -v
5.5
pyinstaller test.py
```

![image](https://user-images.githubusercontent.com/2202306/195485871-06149d5f-2e75-4679-ad4c-c607b9d70bbd.png)

**Comment by Cemos-121** [comment]
Im sorry. I am apparently using an out of date pyinstaller. Thank you for the fast response!
